### ISSUE TITLE
register method not called

### ISSUE THREAD

**Issue by dragu** [yidas/codeigniter-psr4-autoload#3]
Hello

I have followed your guide in CI 3.1.6 but it didn't work.

I couldn't find the 

> \yidas\Psr4Autoload::register();

 call anywhere so I added it right after loading the autoloader and it helped.

**Comment by rohanshukla94** [comment]
Hi, is this still usable?

**Comment by yidas** [comment]
Hi,

In version 2.0.0, you only need to install according to the instructions, and no longer need to call `\yidas\Psr4Autoload::register();` anymore:
https://github.com/yidas/codeigniter-psr4-autoload#installation

**Comment by rohanshukla94** [comment]
Hi, can I use this package and add Eloquent on it? I am coming from Laravel background and I'd love to know more about this.
